import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate, Link } from 'react-router-dom';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  Trophy, ClipboardList, CheckCircle2, Clock, 
  ArrowUpRight, Loader2, BookOpen, AlertCircle, ArrowRight 
} from 'lucide-react';

const Assessments = () => {
  const navigate = useNavigate();
  const [grades, setGrades] = useState<any[]>([]);
  const [courses, setCourses] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Helper to get Auth Headers
  const getAuthHeader = () => ({
    headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }
  });

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [gradesRes, coursesRes] = await Promise.all([
          axios.get('http://localhost:8000/api/user/grades', getAuthHeader()),
          axios.get('http://localhost:8000/api/courses', getAuthHeader())
        ]);
        setGrades(gradesRes.data);
        setCourses(coursesRes.data);
      } catch (err) {
        console.error("Assessment Fetch Error:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  // --- LOGIC: Calculate Proficiency ---
  const averageScore = grades.length > 0 
    ? (grades.reduce((acc, curr) => acc + curr.score, 0) / grades.length).toFixed(1) 
    : "0";

  // --- PDF EXPORT LOGIC ---
  const handleExportPDF = () => {
    const doc = new jsPDF();
    const studentName = localStorage.getItem('full_name') || 'Ademy Student';
    const dateStr = new Date().toLocaleDateString();

    // 1. SLEEK HEADER: Dark Mode Aesthetic
    doc.setFillColor(15, 23, 42); // Slate-900 (Deep Navy)
    doc.rect(0, 0, 210, 50, 'F');
    
    // Logo & Branding
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text("ADEMY", 15, 30);
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(148, 163, 184); // Slate-400
    doc.text("INTELLIGENT E-LEARNING ECOSYSTEM", 15, 38);
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text("OFFICIAL PERFORMANCE TRANSCRIPT", 135, 30);
    doc.text(`ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}`, 135, 36);

    // 2. STUDENT INFORMATION SECTION
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("ACADEMIC RECORD", 15, 65);
    
    doc.setDrawColor(226, 232, 240); // Slate-200
    doc.line(15, 68, 195, 68);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`FULL NAME: ${studentName.toUpperCase()}`, 15, 78);
    doc.text(`DATE ISSUED: ${dateStr}`, 15, 84);
    
    // Big Score Badge in PDF
    doc.setFillColor(240, 253, 244); // Emerald-50
    doc.roundedRect(140, 72, 55, 20, 3, 3, 'F');
    doc.setTextColor(5, 150, 105); // Emerald-600
    doc.setFont("helvetica", "bold");
    doc.text("AVG PROFICIENCY", 145, 78);
    doc.setFontSize(16);
    doc.text(`${averageScore}%`, 145, 86);

    // 3. THE GRADES TABLE
    const tableRows = grades.map((g, i) => [
        `Module 0${g.module_id}`,
        "Automated AI Evaluation",
        new Date(g.taken_at).toLocaleDateString(),
        g.score >= 50 ? 'DISTINCTION' : 'NEEDS REVIEW',
        `${g.score}%`
    ]);

    autoTable(doc, {
      startY: 105,
      head: [['MODULE', 'EVALUATION TYPE', 'DATE', 'STATUS', 'SCORE']],
      body: tableRows,
      theme: 'plain',
      headStyles: { 
        fillColor: [15, 23, 42], // Slate-900
        textColor: [255, 255, 255],
        fontSize: 9,
        fontStyle: 'bold',
        halign: 'center',
        cellPadding: 4
      },
      styles: { 
        fontSize: 9, 
        cellPadding: 6,
        halign: 'center',
        textColor: [71, 85, 105] // Slate-600
      },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: [15, 23, 42] },
        4: { fontStyle: 'bold', textColor: [16, 185, 129] }
      },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });

    // 4. FOOTER & VERIFICATION
    const finalY = (doc as any).lastAutoTable.finalY || 180;
    
    // Summary Box
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(15, finalY + 10, 180, 25, 3, 3, 'F');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "italic");
    doc.text("Verification Statement:", 20, finalY + 18);
    doc.text("This document is generated by the Ademy Neural Engine. Scores are calculated based on weighted module performance", 20, finalY + 24);
    doc.text("and real-time student engagement metrics. This is a secure digital record.", 20, finalY + 28);

    // Signature Line
    doc.setDrawColor(203, 213, 225);
    doc.line(140, finalY + 60, 195, finalY + 60);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    doc.text("AI REGISTRAR VERIFIED", 148, finalY + 65);

    // 5. DOWNLOAD
    doc.save(`ADEMY_TRANSCRIPT_${studentName.replace(/\s/g, '_')}.pdf`);
  };

  const completedModuleIds = grades.map(g => g.module_id);
  const pendingEvaluation = { 
    title: "Complexity Analysis Quiz", 
    course: "Data Structures", 
    code: "DSA", 
    moduleId: 1 
  };

  if (loading) return (
    <div className="h-96 flex flex-col items-center justify-center gap-4">
      <Loader2 className="animate-spin text-emerald-500" size={48} />
      <p className="font-black text-slate-400 uppercase tracking-widest text-xs">Accessing Records...</p>
    </div>
  );

  return (
    <div className="max-w-7xl mx-auto space-y-10 pb-20 font-sans px-4">
      
      {/* 1. TOP SUMMARY CARD */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tighter leading-tight">Assessments</h1>
          <p className="text-slate-500 font-medium mt-2 text-lg">Official performance tracking and examination results.</p>
        </div>

        <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="bg-emerald-500 p-8 rounded-[3rem] text-white shadow-2xl shadow-emerald-200 relative overflow-hidden flex items-center gap-8">
            <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2" />
            <div className="w-20 h-20 bg-white/20 rounded-[2rem] flex items-center justify-center backdrop-blur-md border border-white/10 shadow-inner">
                <Trophy size={40} />
            </div>
            <div>
                <p className="text-[10px] font-black uppercase tracking-[0.3em] text-emerald-100 mb-1">Mean Proficiency</p>
                <h2 className="text-5xl font-black">{averageScore}%</h2>
            </div>
        </motion.div>
      </div>

      {/* 2. PENDING TASKS */}
      <div className="bg-white p-8 md:p-12 rounded-[3.5rem] border border-slate-100 shadow-sm">
        <div className="flex items-center gap-4 mb-10">
            <div className="w-12 h-12 bg-amber-50 text-amber-600 rounded-2xl flex items-center justify-center border border-amber-100 shadow-sm">
                <Clock size={24} />
            </div>
            <div>
                <h3 className="text-2xl font-black text-slate-900 tracking-tight">Active Evaluations</h3>
                <p className="text-sm font-bold text-slate-400 uppercase tracking-widest leading-none mt-1">Awaiting Submission</p>
            </div>
        </div>

        <div className="space-y-4">
            {!completedModuleIds.includes(pendingEvaluation.moduleId) ? (
                <div className="flex flex-col md:flex-row md:items-center justify-between p-8 bg-slate-50 rounded-[2.5rem] border border-slate-100 group hover:border-emerald-500 hover:bg-white hover:shadow-xl transition-all duration-500">
                    <div className="flex items-center gap-6 mb-6 md:mb-0">
                        <div className="w-16 h-16 bg-white rounded-3xl flex items-center justify-center shadow-md font-black text-emerald-500 text-xl italic group-hover:scale-110 transition-transform">
                            {pendingEvaluation.code}
                        </div>
                        <div>
                            <p className="font-black text-xl text-slate-900 leading-tight">{pendingEvaluation.title}</p>
                            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mt-2">{pendingEvaluation.course} • Module 01</p>
                        </div>
                    </div>
                    <button onClick={() => navigate(`/dashboard/quiz/${pendingEvaluation.moduleId}`)} className="bg-slate-900 text-white px-10 py-4 rounded-2xl font-black text-sm uppercase tracking-widest group-hover:bg-emerald-600 transition-all shadow-xl active:scale-95 flex items-center gap-2">
                        Start Now <ArrowRight size={18} />
                    </button>
                </div>
            ) : (
                <div className="p-14 text-center bg-slate-50 rounded-[3rem] border border-dashed border-slate-200 text-slate-400">
                    <CheckCircle2 size={48} className="mx-auto text-emerald-500 mb-4 opacity-40" />
                    <p className="font-black uppercase tracking-[0.2em] text-[10px]">All Evaluations Completed</p>
                </div>
            )}
        </div>
      </div>

      {/* 3. TRANSCRIPT HISTORY */}
      <div className="bg-white p-8 md:p-12 rounded-[4rem] border border-slate-100 shadow-sm relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-12 gap-4 relative z-10">
            <div className="flex items-center gap-4">
                <div className="w-12 h-12 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center border border-blue-100 shadow-sm">
                    <ClipboardList size={24} />
                </div>
                <div>
                    <h3 className="text-2xl font-black text-slate-900 tracking-tight">Examination History</h3>
                    <p className="text-sm font-bold text-slate-400 uppercase tracking-widest leading-none mt-1">Verified AI Results</p>
                </div>
            </div>
            <button 
                onClick={handleExportPDF}
                className="bg-slate-900 text-white px-10 py-4 rounded-[2rem] font-black text-[10px] uppercase tracking-[0.25em] hover:bg-emerald-600 transition-all flex items-center gap-3 shadow-xl active:scale-95"
            >
                Export Transcript <ArrowUpRight size={14}/>
            </button>
        </div>

        <div className="overflow-x-auto relative z-10">
            <table className="w-full text-left">
                <thead>
                    <tr className="text-[11px] font-black uppercase tracking-[0.3em] text-slate-300 border-b border-slate-100">
                        <th className="pb-8 pl-4">Evaluation</th>
                        <th className="pb-8">Timestamp</th>
                        <th className="pb-8">Academic Status</th>
                        <th className="pb-8 pr-4 text-right">Result</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                    {grades.length === 0 ? (
                        <tr><td colSpan={4} className="py-20 text-center font-black text-slate-300 uppercase tracking-widest text-xs italic">No examination records found</td></tr>
                    ) : (
                        grades.map((g, i) => (
                            <tr key={i} className="group hover:bg-slate-50/50 transition-colors">
                                <td className="py-8 pl-4">
                                    <p className="font-black text-slate-900 text-lg leading-tight tracking-tight">Module {g.module_id} Evaluation</p>
                                    <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Automated System Grade</p>
                                </td>
                                <td className="py-8 text-sm font-bold text-slate-500 italic">
                                    {new Date(g.taken_at).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' })}
                                </td>
                                <td className="py-8">
                                    <span className={`px-5 py-2 rounded-full text-[10px] font-black uppercase tracking-[0.2em] border ${g.score >= 50 ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-red-50 text-red-600 border-red-100'}`}>
                                        {g.score >= 50 ? 'Distinction' : 'Needs Review'}
                                    </span>
                                </td>
                                <td className="py-8 pr-4 text-right">
                                    <div className="flex flex-col items-end">
                                        <p className="text-3xl font-black text-slate-900">{g.score}%</p>
                                        <div className="w-24 h-1 bg-slate-100 rounded-full mt-2 overflow-hidden">
                                            <div className={`h-full ${g.score >= 50 ? 'bg-emerald-500' : 'bg-red-500'}`} style={{ width: `${g.score}%` }} />
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        ))
                    )}
                </tbody>
            </table>
        </div>
      </div>
    </div>
  );
};

export default Assessments;